version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/login
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/signup
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/

  prisma-studio:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5555:5555
    command: npm run prisma:studio
    volumes:
      - .:/app
      - /app/node_modules

  ngrok:
    image: ngrok/ngrok
    command: http --domain=${NGROK_DOMAIN} app:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}

  db:
    image: postgres:16.1-alpine3.19
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db-data:
