allowBuilds:
  '@clerk/shared': true
  '@prisma/client': true
  '@prisma/engines': true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
patchedDependencies:
  '@radix-ui/react-scroll-area@1.2.18': patches/@radix-ui__react-scroll-area@1.2.18.patch
